### PR TITLE
Fix two bugs : enums and longs

### PR DESCRIPTION
**Pull request by Igosuki**
- enums can be aliased with namespaces. 
- longs can be longer than 10, somehow our ms timestamps were getting truncated, this is a fix

### CODE REVIEW

**Comment by mikepk** [comment]
Hey! thanks for the PR. Any chance you can create a test case that shows the truncation issue and add it to the test suite? Your pull request finally motivated me to finish porting the apache test suite to Python 3 and getting the Travis CI pipeline working. 

I also want to run a couple of performance tests. You stripped out some of the the type casting I did in the zig-zag encoding which was intended to remove the extra python dynamic code inside of Cython. I'm not convinced it's actually slower without it but want to test it.

**Comment by mikepk** [comment]
I tried to create a long truncation and it doesn't seem to exhibit the behavior you describe.

```python
from six import BytesIO
import spavro.io
import json
from spavro.io import FastDatumWriter
import io

fastbuff = BytesIO()
fastencoder = spavro.io.FastBinaryEncoder(fastbuff)

write_schema = spavro.schema.parse(json.dumps("long"))

# largest 64 bit unsigned integer (avro long)
value = 9223372036854775807
fdw = FastDatumWriter()
fdw.write_data(write_schema, value, fastencoder)
avro_encoded_value = fastbuff.getvalue()

reader = spavro.io.DatumReader(write_schema)
bytes_reader = io.BytesIO(avro_encoded_value)
decoder = spavro.io.BinaryDecoder(bytes_reader)

decoded_value = reader.read(decoder)
print("Before encoding: {}, After encoding and decoding: {}. The same? {}".format(value, decoded_value, value == decoded_value))
assert decoded_value == value
```
Output
```
Before encoding: 9223372036854775807, After encoding and decoding: 9223372036854775807. The same? True
assert decoded_value == value
```

**Comment by mikepk** [comment]
So I couldn't reproduce the issue you reported but I think I got to the root of it. I don't believe your fix actually fixed the issue. I think the real problem was the function signature in the cython fast reader https://github.com/pluralsight/spavro/blob/4512c84c385246d443af80163372a8bd59e8e0f6/src/spavro/fast_binary.pyx#L9 where the return type was `long`. On 64 bit systems a signed long and a signed long long are synonymous. On a 32 bit system a signed long would max out at 2147483648 (which has 10 digits) which is where I assume you were hitting the truncation. I've changed the Cython function signature to return a long long so now it should work on 32 bit systems as well. The latest version of spavro should fix this issue.

**Comment by mikepk** [comment]
I'm going to assume my fix fixed the truncation issue since i've not heard anything from the original pull requestor re: test case etc... I also added in the enum fix so all the issues should be fixed in the main branch. Closing this PR unless someone hits this issue again.

**Comment by Igosuki** [comment]
Sorry I haven't had the time to meaningfully reproduce it, I can try to run
my code against the current master see if it works fine ?

**Comment by mikepk** [comment]
That would be awesome, thanks! My theory is that you're running a 32bit system/python and that, combined with a function signature bug, was what you were seeing. It should be fixed now on both 32 and 64bit systems.

**Pull request closed without merging**
